---
- hosts: all
  sudo: True
  tasks: 
  - name: Set dns node as primary nameserver
    copy: >
      src=files/etc/resolv.conf
      dest=/etc/resolv.conf
      owner=root
      group=root
      mode=644

  - name: Ensure ntp is installed and nodes are updated
    apt: pkg=ntp update_cache=yes