---
- hosts: all
  sudo: True
  tasks: 
  - name: Update apt
    apt: update_cache=yes

  - name: Setting dns node as primary nameserver
    copy: >
      src=files/etc/resolv.conf
      dest=/etc/resolv.conf
      owner=root
      group=root
      mode=644
      