---
- name: Corosync and pacemaker installation
  hosts: webservers
  sudo: True
  tasks:
  - name: Ensure corosync and pacemaker are installed
    apt: pkg={{ item }}
    with_items:
      - corosync
      - pacemaker
      
  - name: Corosync authentication key copy
    copy: >
      src=files/etc/corosync/authkey
      dest=/etc/corosync/authkey
      owner=root
      group=root
      mode=400
    notify:
      - restart corosync
      
  - name: Heartbeat address configuration
    copy: >
      src=files/etc/corosync/corosync.conf
      dest=/etc/corosync/corosync.conf
      owner=root
      group=root
      mode=644
    notify:
      - restart corosync

  - name: Corosync default file
    copy: >
      src=files/etc/default/corosync
      dest=/etc/default/corosync
      owner=root
      group=root
      mode=644
    notify:
      - restart corosync

  handlers:
  - name: restart corosync
    service: name=corosync state=restarted

- name: Setting pacemaker resources
  hosts: nodo1
  sudo: True
  tasks:
  - name: Copy pacemaker resource dump file to node1
    copy: >-
      src=files/pacemaker.dump
      dest=/var/tmp/pacemaker.dump
      owner=root
      group=root
  - name: Setting pacemaker resources with crm
    command: /usr/sbin/crm configure load update /var/tmp/pacemaker.dump