---
- name: iSCSI target
  hosts: dns
  sudo: True
  tasks:
  - name: Ensure tgt is installed
    apt: name={{ item }}
    with_items:
      - tgt
      
  # - name: Modify iscsitarget default file
  #   copy: >-
  #     src=files/etc/default/iscsitarget
  #     dest=/etc/default/iscsitarget
  #     owner=root
  #     group=root
  #     mode=644

  - name: Start tgt
    service: name=tgt state=started

  - name: Create a target
    command: >-
      tgtadm --lld iscsi --op new --mode target --tid 1 -T iqn.2001-04.com.example:shared1
    ignore_errors: yes
      
  - name: Add a LUN to the target
    command: >-
      tgtadm --lld iscsi --op new --mode logicalunit --tid 1 --lun 1 -b /dev/sdb
    ignore_errors: yes

  - name: Ensure all initiators are accepted
    command: tgtadm --lld iscsi --op bind --mode target --tid 1 -I ALL
    ignore_errors: yes
  
- name: iSCSI initiators
  hosts: webservers
  sudo: True
  tasks:
  - name: Ensure open-iscsi is installed
    apt: name=open-iscsi

  - name: Open a session to the target iqn.2001-04.com.example:shared1
    open_iscsi: >
      portal=10.1.1.103
      discover=yes
      target=iqn.2001-04.com.example:shared1
      login=yes
